const CONTENT_OPTIONS = [
  { value: "Adição", dataTokens: "somar" },
  { value: "Conjuntos" },
  {
    value: "Conjuntos Numéricos",
    dataTokens:
      "Numéricos Complexos Racionais Reais Naturais Irracionais Inteiros",
  },
  { value: "Critérios de Divisibilidade" },
  { value: "Divisão" },
  { value: "Divisão de Frações" },
  { value: "Equação do Primeiro Grau" },
  { value: "Equação do Segundo Grau" },
  { value: "Estatística" },
  { value: "Expressões Numéricas" },
  { value: "Frações" },
  { value: "Geometria", dataTokens: "Formas Geométricas" },
  {
    value: "Geometria Espacial",
    dataTokens: "Cilindro Cubo Cone Esfera Paralelepípedo",
  },
  {
    value: "Geometria Plana",
    dataTokens:
      "Ângulos Bissetriz Mediatriz Paralelogramo Retas Quadrado Retângulo Trapézio Triângulo",
  },
  { value: "Inequação" },
  { value: "Juros Compostos" },
  { value: "Juros Simples" },
  { value: "Matrizes" },
  { value: "MDC: Máximo Divisor Comum" },
  { value: "MMC: Mínimo Múltiplo Comum" },
  { value: "Multiplicação" },
  { value: "Multiplicação de Frações" },
  { value: "Números Decimais" },
  { value: "Números Primos" },
  { value: "Potenciação" },
  { value: "PA: Progressão Aritmética" },
  { value: "PG: Progressão Geométrica" },
  { value: "Plano Cartesiano" },
  { value: "Porcentagem" },
  { value: "Produtos Notáveis" },
  { value: "Radiciação" },
  { value: "Razão e Proporção" },
  { value: "Sistemas Lineares" },
  { value: "Soma de Frações" },
  { value: "Subtração" },
  { value: "Subtração de Frações" },
  { value: "Tabuada" },
  { value: "Triângulo de Pascal" },
  { value: "Trigonometria", dataTokens: "Seno Cosseno Tangente" },
  { value: "Unidades de Medida" },
  { value: "Outros" },
];

export default CONTENT_OPTIONS;
